<a href="https://colab.research.google.com/github/jejec0703/NLP-Natural-Language-Processing/blob/master/%EC%8B%A4%EC%8A%B5_%EC%97%B0%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
docs = ['나는 양념 치킨을 좋아해 하지만 후라이드 치킨은 싫어해',
        '나는 후라이드 치킨을 좋아해 하지만 양념 치킨을 싫어해']

In [ ]:
doc_ls = [doc.split() for doc in docs]
doc_ls

[['나는', '양념', '치킨을', '좋아해', '하지만', '후라이드', '치킨은', '싫어해'],
 ['나는', '후라이드', '치킨을', '좋아해', '하지만', '양념', '치킨을', '싫어해']]

In [ ]:
from collections import defaultdict

word2id = defaultdict(lambda : len(word2id))
[word2id[token] for doc in doc_ls for token in doc]
word2id

defaultdict(<function __main__.<lambda>>,
            {'나는': 0,
             '싫어해': 7,
             '양념': 1,
             '좋아해': 3,
             '치킨은': 6,
             '치킨을': 2,
             '하지만': 4,
             '후라이드': 5})

In [ ]:
import numpy as np

BoW_ls = []
for doc in doc_ls:
  bow = np.zeros(len(word2id), dtype=int)
  for token in doc:
    bow[word2id[token]] += 1
  BoW_ls.append(bow)
BoW_ls

[array([1, 1, 1, 1, 1, 1, 1, 1]), array([1, 1, 2, 1, 1, 1, 0, 1])]

In [ ]:
docs = ['오늘 동물원에서 원숭이를 봤어',
        '오늘 동물원에서 코끼리를 봤어 봤어',
        '동물원에서 원숭이에게 바나나를 봤어 바나나를']

In [ ]:
doc_ls = [doc.split() for doc in docs]
doc_ls

[['오늘', '동물원에서', '원숭이를', '봤어'],
 ['오늘', '동물원에서', '코끼리를', '봤어', '봤어'],
 ['동물원에서', '원숭이에게', '바나나를', '봤어', '바나나를']]

In [ ]:
from collections import defaultdict

word2id = defaultdict(lambda : len(word2id))
[word2id[token] for doc in doc_ls for token in doc]
word2id

defaultdict(<function __main__.<lambda>>,
            {'동물원에서': 1,
             '바나나를': 6,
             '봤어': 3,
             '오늘': 0,
             '원숭이를': 2,
             '원숭이에게': 5,
             '코끼리를': 4})

In [ ]:
import numpy as np

BoW_ls = []
for doc in doc_ls:
  bow = np.zeros(len(word2id), dtype=int)
  for token in doc:
    bow[word2id[token]] += 1
  BoW_ls.append(bow)
BoW_ls

[array([1, 1, 1, 1, 0, 0, 0]),
 array([1, 1, 0, 2, 1, 0, 0]),
 array([0, 1, 0, 1, 0, 1, 2])]

### CounterVectorize

In [ ]:
docs = ['오늘 동물원에서 원숭이를 봤어',
        '오늘 동물원에서 코끼리를 봤어 봤어',
        '동물원에서 원숭이에게 바나나를 줬어 바나나를']

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
count_vect = CountVectorizer()
BoW = count_vect.fit_transform(docs)
BoW.toarray()

array([[1, 0, 1, 1, 1, 0, 0, 0],
       [1, 0, 2, 1, 0, 0, 0, 1],
       [1, 2, 0, 0, 0, 1, 1, 0]])

In [ ]:
BoW.toarray()[0]

array([1, 0, 1, 1, 1, 0, 0, 0])

In [ ]:
from IPython.core import display as ICD
## 데이터 프레임 보여주는 것
import pandas as pd
vocab = count_vect.get_feature_names()
for i in range(len(docs)):
  print('문서 {} : {}'.format(i, docs[i]))
  ICD.display(pd.DataFrame([BoW.toarray()[i]], columns=vocab))
  print('\n\n')

문서 0 : 오늘 동물원에서 원숭이를 봤어


동물원에서  바나나를  봤어  오늘  원숭이를  원숭이에게  줬어  코끼리를
0      1     0   1   1     1      0   0     0




문서 1 : 오늘 동물원에서 코끼리를 봤어 봤어


동물원에서  바나나를  봤어  오늘  원숭이를  원숭이에게  줬어  코끼리를
0      1     0   2   1     0      0   0     1




문서 2 : 동물원에서 원숭이에게 바나나를 줬어 바나나를


동물원에서  바나나를  봤어  오늘  원숭이를  원숭이에게  줬어  코끼리를
0      1     2   0   0     0      1   1     0

### gensim

In [ ]:
!pip install gensim

In [ ]:
import gensim
from gensim import corpora

In [ ]:
docs = ['오늘 동물원에서 원숭이를 봤어',
        '오늘 동물원에서 코끼리를 봤어 봤어',
        '동물원에서 원숭이에게 바나나를 줬어 바나나를']

In [ ]:
doc_ls = [doc.split() for doc in docs]
doc_ls

[['오늘', '동물원에서', '원숭이를', '봤어'],
 ['오늘', '동물원에서', '코끼리를', '봤어', '봤어'],
 ['동물원에서', '원숭이에게', '바나나를', '줬어', '바나나를']]

In [ ]:
id2word = corpora.Dictionary(doc_ls)
## id 가 있고 그에 매칭되는 단어

BoW = [id2word.doc2bow(doc) for doc in doc_ls]
## 사전을 생산한거에 doc2bow 를 하면 BoW 를 만들어줌

In [ ]:
BoW

[[(0, 1), (1, 1), (2, 1), (3, 1)],
 [(0, 1), (1, 2), (2, 1), (4, 1)],
 [(0, 1), (5, 2), (6, 1), (7, 1)]]

In [ ]:
'''[[(0, 1), (1, 1), (2, 1), (3, 1)],  # 1번 인덱스 2번 3번 4번 인덱스가 나옴
   [(0, 1), (1, 2), (2, 1), (4, 1)],
   [(0, 1), (5, 2), (6, 1), (7, 1)]]'''

In [ ]:
from gensim.matutils import sparse2full
from IPython.core import display as ICD

id2word.keys()

[0, 1, 2, 3, 4, 5, 6, 7]

In [ ]:
for i in range(len(id2word.keys())):
  print(id2word[i])

동물원에서
봤어
오늘
원숭이를
코끼리를
바나나를
원숭이에게
줬어


In [ ]:
from gensim.matutils import sparse2full
from IPython.core import display as ICD

vocab = [id2word[i] for i in id2word.keys()]
for i in range(len(docs)) :
  print("문서{} : {}".format(i, docs[i]))
  ICD.display(pd.DataFrame([sparse2full(BoW[i], len(vocab))], columns=vocab))
  print("\n\n")

문서0 : 오늘 동물원에서 원숭이를 봤어


동물원에서   봤어   오늘  원숭이를  코끼리를  바나나를  원숭이에게   줬어
0    1.0  1.0  1.0   1.0   0.0   0.0    0.0  0.0




문서1 : 오늘 동물원에서 코끼리를 봤어 봤어


동물원에서   봤어   오늘  원숭이를  코끼리를  바나나를  원숭이에게   줬어
0    1.0  2.0  1.0   0.0   1.0   0.0    0.0  0.0




문서2 : 동물원에서 원숭이에게 바나나를 줬어 바나나를


동물원에서   봤어   오늘  원숭이를  코끼리를  바나나를  원숭이에게   줬어
0    1.0  0.0  0.0   0.0   0.0   2.0    1.0  1.0

### TDM

In [ ]:
docs = ['오늘 동물원에서 원숭이를 봤어',
        '오늘 동물원에서 코끼리를 봤어 봤어',
        '동물원에서 원숭이에게 바나나를 줬어 바나나를']

In [ ]:
doc_ls = [doc.split() for doc in docs]
doc_ls

[['오늘', '동물원에서', '원숭이를', '봤어'],
 ['오늘', '동물원에서', '코끼리를', '봤어', '봤어'],
 ['동물원에서', '원숭이에게', '바나나를', '줬어', '바나나를']]

In [ ]:
cv = CountVectorizer()
cv

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [ ]:
tdm = cv.fit_transform(docs)

In [ ]:
tdm

<3x8 sparse matrix of type '<class 'numpy.int64'>'
	with 12 stored elements in Compressed Sparse Row format>

In [ ]:
cv.get_feature_names()

['동물원에서', '바나나를', '봤어', '오늘', '원숭이를', '원숭이에게', '줬어', '코끼리를']

In [ ]:
from collections import defaultdict
word2id = defaultdict(lambda : len(word2id))
[word2id[token] for doc in doc_ls for token in doc]
word2id

defaultdict(<function __main__.<lambda>>,
            {'동물원에서': 1,
             '바나나를': 6,
             '봤어': 3,
             '오늘': 0,
             '원숭이를': 2,
             '원숭이에게': 5,
             '줬어': 7,
             '코끼리를': 4})

In [ ]:
import numpy as np

TDM = np.zeros((len(word2id), len(doc_ls)), dtype=int)
for i, doc in enumerate(doc_ls):
  for token in doc:
    TDM[word2id[token], i] += 1
TDM

array([[1, 1, 0],
       [1, 1, 1],
       [1, 0, 0],
       [1, 2, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 2],
       [0, 0, 1]])

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

count_vect = CountVectorizer()
DTM = CountVectorizer()
DTM = count_vect.fit_transform(docs)
DTM.T.toarray()

array([[1, 1, 1],
       [0, 0, 2],
       [1, 2, 0],
       [1, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0]])